services:
 postgres:
  container_name: postgres
  network_mode: bridge
  image: postgres:latest
  restart: unless-stopped
  shm_size: 128mb
  environment:
   POSTGRES_PASSWORD: root
   POSTGRES_USER: root
  # volumes:
  #  - ./.postgres:/var/lib/postgresql/data
  ports:
   - '5432:5432'
